# Generated by Django 3.2.3 on 2021-05-23 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='address',
            field=models.TextField(blank=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='country',
            field=models.CharField(blank=True, max_length=100, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='date_of_birth',
            field=models.DateField(blank=True, verbose_name='Date of birth'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='gender',
            field=models.CharField(blank=True, max_length=20, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Last name'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='mobile',
            field=models.CharField(blank=True, max_length=20, verbose_name='Mobile'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, verbose_name='Postal Code'),
        ),
    ]
