# Generated by Django 3.2.3 on 2021-05-24 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('merchandise', '0001_initial'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='merchandises',
            field=models.ManyToManyField(blank=True, null=True, to='merchandise.Merchandise'),
        ),
    ]
