# Generated by Django 3.2.3 on 2021-05-24 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tags', '0001_initial'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Merchandise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('photo', models.ImageField(upload_to='')),
                ('discount', models.IntegerField(default=0)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('events', models.ManyToManyField(blank=True, null=True, to='events.Event')),
                ('tags', models.ManyToManyField(blank=True, null=True, to='tags.Tag')),
            ],
        ),
    ]
