# Generated by Django 3.2.3 on 2021-05-24 16:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('merchandise', '0001_initial'),
        ('events', '0002_event_merchandises'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.IntegerField()),
                ('service_fee', models.IntegerField()),
                ('transaction_fee', models.IntegerField()),
                ('status', models.IntegerField(choices=[(1, 'Approved'), (2, 'Pending'), (3, 'Shipping'), (4, 'Processing'), (5, 'Cancelled')])),
                ('last_update', models.DateTimeField(default=datetime.datetime(2021, 5, 24, 16, 58, 58, 596353, tzinfo=utc))),
                ('payment_method', models.CharField(max_length=50)),
                ('events', models.ManyToManyField(to='events.Event')),
                ('merchandise', models.ManyToManyField(to='merchandise.Merchandise')),
            ],
        ),
    ]
